# Generated by Django 4.0.3 on 2022-04-10 09:18

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='کد ملی')),
                ('branch', models.CharField(choices=[('100', 'Branch 100'), ('101', 'Branch 101'), ('102', 'Branch 102')], max_length=3)),
                ('transaction_value', models.PositiveIntegerField()),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
            ],
        ),
    ]
