# Generated by Django 4.0.3 on 2022-04-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='branch',
            field=models.CharField(choices=[('100', 'شعبه ۱۰۰'), ('101', 'شعبه ۱۰۱'), ('102', 'شعبه ۱۰۲')], max_length=3, verbose_name='کد شعبه'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_value',
            field=models.PositiveIntegerField(verbose_name='ارزش معامله'),
        ),
    ]
