# Generated by Django 4.0.3 on 2022-04-10 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0002_alter_transaction_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='national_id',
            field=models.CharField(max_length=10, verbose_name='کد ملی'),
        ),
    ]
